# Generated by Django 3.1.6 on 2021-02-07 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.card')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
