# Generated by Django 3.1.6 on 2021-02-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cardimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardimage',
            name='descriptors',
            field=models.TextField(default=''),
        ),
    ]
