# Generated by Django 3.1.6 on 2021-02-07 13:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cardimage_descriptors'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardFace',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descriptors', models.TextField(default='')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='type',
        ),
        migrations.DeleteModel(
            name='CardImage',
        ),
        migrations.AddField(
            model_name='cardface',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.card'),
        ),
    ]
