# Generated by Django 3.1.6 on 2021-02-07 14:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20210207_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardface',
            old_name='type',
            new_name='face_type',
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('card_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardface')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
