# Generated by Django 3.1.6 on 2021-02-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20210207_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardface',
            old_name='face_type',
            new_name='layout',
        ),
    ]
