# Generated by Django 3.1.6 on 2021-02-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20210207_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardface',
            name='layout',
        ),
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
