# Generated by Django 3.1.6 on 2021-02-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20210207_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardface',
            name='illustration_id',
            field=models.CharField(default='', max_length=48),
        ),
    ]
