# Generated by Django 3.1.6 on 2021-02-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_cardface_illustration_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardtype',
            old_name='card_face',
            new_name='face',
        ),
    ]
