# Generated by Django 3.1.6 on 2021-02-07 15:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20210207_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descriptors', models.TextField(default='')),
                ('illustration_id', models.CharField(default='', max_length=48)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cards.face')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='face',
        ),
        migrations.AlterField(
            model_name='card',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cards.card'),
        ),
        migrations.DeleteModel(
            name='CardFace',
        ),
        migrations.DeleteModel(
            name='CardType',
        ),
        migrations.AddField(
            model_name='face',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cards.card'),
        ),
    ]
