# Generated by Django 3.1.6 on 2021-02-07 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20210207_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='faces', to='cards.card'),
        ),
    ]
