# Generated by Django 3.1.6 on 2021-02-07 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_auto_20210207_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='type',
            name='face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='cards.face'),
        ),
    ]
