# Generated by Django 3.1.6 on 2021-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_card_collector_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
